name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version_level:
        description: Increment level of version
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  version_bump:
    name: Increment version and publish on crates.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-release
        uses: taiki-e/install-action@cargo-release

      - name: Publish crate and push tag
        run: cargo release -vv ${{ inputs.version_level }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

