name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version_level:
        description: Increment level of version
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  version_bump:
    name: Increment version and publish on crates.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set Git username and email
        run: 
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # This action doesn't support cargo-release specifically, but uses a fallback
      # mechanism that works just fine. For more information:
      # https://github.com/taiki-e/install-action
      - name: Install cargo-release
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-release

      - name: Run cargo-release to update repo and crates.io
        run: cargo release --no-verify --no-confirm --execute ${{ inputs.version_level }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
